# Uncomment the next line to define a global platform for your project
 platform :ios, '11.4'

target 'Bazaaroh' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Bazaaroh
  pod 'GoogleSignIn'
  # pod 'FacebookSDK'
  # pod 'FBSDKLoginKit'
  end

 
